@startuml
title Diagramme de classe
' skinparam linetype ortho

class Partenaire{
    # nom : String
    # adresse: String
    + offrir(cadeau : AProduit, client : Client)
    + vendre(produit : Produit, client : Client)
    + catalogueProduits() : ArrayList<Produit>
}

class Zone{
    # nom : String
    # code_postal : String
}

class Abonne{
    vup : boolean
    + acheter (produit : Produit)
    + chargerCarte (carte : CarteInfidelite)
    + recupererCadeau (cadeau : Cadeau, carte : CarteInfidelite)
}

class Client{
    + acheter (produit : Produit)
}

class CarteInfidelite{
    montant : double
    nombrePoint : int
    chargement (montant : int )
    nouvelleAchat(montant :floar)
    listePatenaire(): ArrayList<Partenaire>
}
class Ville{
    # nom :String
    # superficie: double
}

package Composite{
    abstract  AProduit{
        getCout():double
    }
    class Produit{
        istrategie : IStrategyCout
        getCout():double
    }
    class CatalogueCadeau{
        getCout() : double
    }
    class Parking{
        #lieu : String
        #prix : double
        /'En heure'/ #durée : double
        getCout() : double
    }
    class TransportCommun{
        #type : Type
        #prix : double
        /'En heure'/ #durée : double
        getCout() : double
    }
    class Cadeau{
        getCout():double
    }
    Produit -left-|> AProduit
    Parking -up-|> Produit
    TransportCommun -up-|> Produit
    Cadeau -up-|> Produit
    CatalogueCadeau -up-|> AProduit
    CatalogueCadeau *-up- "1..*" AProduit

}


package Strategie{
    class ReductionParkingStartegy
    class TransportCommunStartegy
    class NormalStrategie
    class DixPourcentPoint{
        getPoint():double
    }
    class DixPourcentCout{
        getCout():double
    }
    interface IStrategyCout{
        getCout() : double
    }
    interface IStrategyPoint
    NormalStrategie .up.|> IStrategyCout
    DixPourcentPoint .up.|> IStrategyPoint
    DixPourcentCout .up.|> IStrategyCout
}

Abonne -up-> "*"CarteInfidelite : possede
Abonne -up-|> Client : est

Ville *-- "*" Zone
Zone *-right- "*" Partenaire
Partenaire -> "*" AProduit : vend ou offre
Produit -> IStrategyCout
Produit -> IStrategyPoint
CarteInfidelite -up-> "*"Partenaire : "est validée"


@enduml

@startuml
title cas1
left to right direction

actor client as C
rectangle "cumul de points" {
    usecase "faire achat" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>

}

C -- UC1
@enduml

@startuml
title cas2
left to right direction

actor client as C
rectangle "Bonus d'infidelite" {
    usecase "Utiliser carte" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>
}

C -- UC1
@enduml

@startuml
title cas3
left to right direction

actor client as C
rectangle "Consulter solde" {
    usecase "consulter solde" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>

}

C -- UC1
@enduml



@startuml
title cas4
left to right direction

actor client as C
rectangle "Catalogue des cadeaux" {
    usecase "consulter annuaire" as UC1
    usecase "Consulter description cadeau" as UC2
    usecase "Consulter description magasin" as UC3

    UC2 .> UC1 : <<extends>>
    UC3 .up.> UC1 : <<extends>>

}

C -- UC1
@enduml

@startuml
title cas5
left to right direction

actor client as C
rectangle "Achat cadeau" {
    usecase "demander offre" as UC1
    usecase "recuperer offre" as UC2
    usecase "valider carte" as UC3

    UC2 .> UC1 : <<extends>>
    UC2 .down.> UC3 : <<include>>

}

C -- UC1
@enduml

