@startuml
title Diagramme de classe
' skinparam linetype ortho

class Partenaire{

    + offrir(cadeau : AProduit, abonne : Abonne)
    + vendre(produit : Produit, client : Client)
    + listeCadeau() : ArrayList<AProduit>
    + listeProduit() : ArrayList<Produit>
}

class Zone{}

class Abonne{
    vup : boolean
    + acheter (produit : Produit)
    + chargerCarte (carte : CarteInfidelite)
    + recupererCadeau (cadeau : Cadeau, carte : CarteInfidelite)
}

class Client{
    + acheter (produit : Produit)
}

class CarteInfidelite{
    montant : double
    nombrePoint : int
    chargement (montant : int )
    nouvelleAchat(montant :floar)
    listePatenaire(): ArrayList<Partenaire>
}
class Ville

package Composite{
    abstract  AProduit{
        getCost():double
    }
    class Produit{
        istrategie : IStrategie
        getCost():double
    }
    class CatalogueCadeau{
        getCost() : double
    }
    class Cadeau{
        getCost():double
    }
    Produit -left-|> AProduit
    Cadeau -up-|> Produit
    CatalogueCadeau -up-|> AProduit
    CatalogueCadeau *-up- "1..*" AProduit
    
}


package Strategie{
    class reductionParking
    class transportCommun
    class NormalStrategie
    interface IStrategie{
        getCost() : double
    }
    reductionParking .up.|> IStrategie
    NormalStrategie .up.|> IStrategie
    transportCommun .up.|> IStrategie
}

Abonne -up-> "*"CarteInfidelite : possede
Abonne -up-|> Client : est

Ville *-left- "*" Zone
Zone *-left- "*" Partenaire
Partenaire -> "*" AProduit : vend ou offre
Produit -> IStrategie
CarteInfidelite -up-> "*"Partenaire : "est validée" 


@enduml

@startuml
title cas1
left to right direction

actor client as C
rectangle "cumul de points" {
    usecase "faire achat" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>

}

C -- UC1
@enduml

@startuml
title cas2
left to right direction

actor client as C
rectangle "Bonus d'infidelite" {
    usecase "Utiliser carte" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>
}

C -- UC1
@enduml

@startuml
title cas3
left to right direction

actor client as C
rectangle "Consulter solde" {
    usecase "consulter solde" as UC1
    usecase "valider carte" as UC2

    UC1 .> UC2 : <<include>>

}

C -- UC1
@enduml



@startuml
title cas4
left to right direction

actor client as C
rectangle "Catalogue des cadeaux" {
    usecase "consulter annuaire" as UC1
    usecase "Consulter description cadeau" as UC2
    usecase "Consulter description magasin" as UC3

    UC2 .> UC1 : <<extends>>
    UC3 .up.> UC1 : <<extends>>

}

C -- UC1
@enduml

@startuml
title cas5
left to right direction

actor client as C
rectangle "Achat cadeau" {
    usecase "demander offre" as UC1
    usecase "recuperer offre" as UC2
    usecase "valider carte" as UC3

    UC2 .> UC1 : <<extends>>
    UC2 .down.> UC3 : <<include>>

}

C -- UC1
@enduml